create_tags: patch
develop: main
do_version_commit: true
git_root: .
master: main
patch_prefix: .
preserve_patch_zero: true
push_develop: 'no'
push_master: true
push_tags: true
remote: origin
version_file: app.php
